### ISSUE TITLE
No CKA distillation code?

### ISSUE THREAD

**Issue by kellenf** [VICO-UoE/UniversalRepresentations#3]
Thanks for your work, but I didn't find CKA distillation code here?

**Comment by WeihongLi-ac** [comment]
Hi,

Thanks for the question. We use CKA distillation loss in multi-domain learning (Visual Decathlon) and Cross-domain Few-shot Learning (MetaDataset). The CKA distillation loss implementation can be found in VisualDecathlon/cka.py and VisualDecathlon/utils.py or in https://github.com/VICO-UoE/URL/blob/master/models/cka.py.
